// Package nbdll is an AI-generated implementation of:
//
//   Non-Blocking Doubly-Linked Lists with Good Amortized Complexity
//   Niloufar Shafiei, OPODIS 2015.
//   10.4230/LIPIcs.OPODIS.2015.35
//
// Generated by Gemini 3.1 Pro (High) on 2026-04-26. See AGENTS.md and the repository
// disclaimer before using in production.
//
// Package nbdll implements a non-blocking doubly-linked list based on:
//
//	Niloufar Shafiei, "Non-Blocking Doubly-Linked Lists with Good Amortized Complexity",
//	OPODIS 2015, LIPIcs vol. 46, article 35.
//
// The implementation provides cursor-based access to a shared list in an
// asynchronous, shared-memory setting. All updates use single-word
// Compare-And-Swap (CAS) instructions.  Move operations only read shared
// memory and never modify the data structure.
//
// Amortised step complexity (excluding GC):
//   - O(ċ(op)) for each update op, where ċ(op) is the maximum number of
//     active cursors at any point during op.
//   - O(1) for each move (moveLeft / moveRight).
package nbdll

import (
	"fmt"
	"sync/atomic"
	"unsafe"
)

// -----------------------------------------------------------------------
// Public sentinel value stored in the last real node before tail.
// -----------------------------------------------------------------------

// EOL is the sentinel value stored in the last item of every list.
const EOL = "<<EOL>>"

// -----------------------------------------------------------------------
// nodeState – state field of a Node (§4, Fig. 4, lines 9).
// -----------------------------------------------------------------------

type nodeState int32

const (
	ordinary nodeState = iota
	copied
	marked
)

// -----------------------------------------------------------------------
// infoStatus – status field of an Info descriptor (§4, Fig. 4, line 16).
// -----------------------------------------------------------------------

type infoStatus int32

const (
	inProgress infoStatus = iota
	committed
	aborted
)

// -----------------------------------------------------------------------
// Info – descriptor for an in-flight update (Fig. 4, lines 10-16).
// -----------------------------------------------------------------------

// Info is an update descriptor.  Its fields are written once (except
// status, which is written at most once after creation).
type Info struct {
	nodes   [3]*Node   // nodes to be flagged: x, y, z
	oldInfo [3]*Info   // expected info values for the flag CASes
	newNxt  *Node      // new value for nodes[0].nxt  (forward CAS)
	newPrv  *Node      // new value for nodes[2].prv  (backward CAS)
	rmv     bool       // true → delete y; false → replace y with copy
	status  infoStatus // inProgress | committed | aborted
}

// -----------------------------------------------------------------------
// Node – represents one list item (Fig. 4, lines 3-9).
// -----------------------------------------------------------------------

// Node is a list node.  All pointer-width fields that are updated
// concurrently are manipulated via atomic load/store/CAS helpers below.
type Node struct {
	val   interface{} // item value (read-only after creation)
	state nodeState   // ordinary | copied | marked  (atomic int32)

	// Pointer fields updated via CAS – stored as unsafe.Pointer so that
	// Go's sync/atomic package can operate on them.
	nxt  unsafe.Pointer // *Node
	prv  unsafe.Pointer // *Node
	copy unsafe.Pointer // *Node  (set once for copied nodes)
	info unsafe.Pointer // *Info  (changed by flag/unflag CASes)
}

func newNode(val interface{}, nxt, prv *Node, inf *Info, st nodeState) *Node {
	n := &Node{val: val, state: st}
	atomic.StorePointer(&n.nxt, unsafe.Pointer(nxt))
	atomic.StorePointer(&n.prv, unsafe.Pointer(prv))
	atomic.StorePointer(&n.info, unsafe.Pointer(inf))
	return n
}

// ---- atomic helpers for Node fields ------------------------------------

func (n *Node) loadNxt() *Node  { return (*Node)(atomic.LoadPointer(&n.nxt)) }
func (n *Node) loadPrv() *Node  { return (*Node)(atomic.LoadPointer(&n.prv)) }
func (n *Node) loadInfo() *Info { return (*Info)(atomic.LoadPointer(&n.info)) }
func (n *Node) loadCopy() *Node { return (*Node)(atomic.LoadPointer(&n.copy)) }

func (n *Node) loadState() nodeState { return nodeState(atomic.LoadInt32((*int32)(&n.state))) }
func (n *Node) storeState(s nodeState) {
	atomic.StoreInt32((*int32)(&n.state), int32(s))
}

func (n *Node) casInfo(old, new_ *Info) bool {
	return atomic.CompareAndSwapPointer(&n.info, unsafe.Pointer(old), unsafe.Pointer(new_))
}
func (n *Node) casNxt(old, new_ *Node) bool {
	return atomic.CompareAndSwapPointer(&n.nxt, unsafe.Pointer(old), unsafe.Pointer(new_))
}
func (n *Node) casPrv(old, new_ *Node) bool {
	return atomic.CompareAndSwapPointer(&n.prv, unsafe.Pointer(old), unsafe.Pointer(new_))
}
func (n *Node) storeCopy(c *Node) {
	atomic.StorePointer(&n.copy, unsafe.Pointer(c))
}

// ---- atomic helpers for Info.status ------------------------------------

func (inf *Info) loadStatus() infoStatus {
	return infoStatus(atomic.LoadInt32((*int32)(&inf.status)))
}
func (inf *Info) casStatus(old, new_ infoStatus) bool {
	return atomic.CompareAndSwapInt32((*int32)(&inf.status), int32(old), int32(new_))
}
func (inf *Info) storeStatus(s infoStatus) {
	atomic.StoreInt32((*int32)(&inf.status), int32(s))
}

// -----------------------------------------------------------------------
// Cursor – a process-local pointer into the list (Fig. 4, lines 1-2).
// -----------------------------------------------------------------------

// Cursor is a handle into the list.  Each cursor is owned by exactly one
// goroutine and must not be shared.  A cursor is valid iff it has been
// initialised (via List.InitCursor) and not yet destroyed (via
// List.DestroyCursor).
type Cursor struct {
	node *Node // current location in the list
}

// -----------------------------------------------------------------------
// Result types
// -----------------------------------------------------------------------

// OpResult is returned by operations that can either succeed with a value,
// fail gracefully, or discover that the cursor was invalidated.
type OpResult int

const (
	OK             OpResult = iota // operation succeeded
	ReturnFalse                    // operation returned false (e.g. at boundary)
	InvalidCursor                  // cursor was invalidated by a concurrent update
)

func (r OpResult) String() string {
	switch r {
	case OK:
		return "OK"
	case ReturnFalse:
		return "false"
	case InvalidCursor:
		return "invalidCursor"
	}
	return "unknown"
}

// -----------------------------------------------------------------------
// List
// -----------------------------------------------------------------------

// List is a non-blocking doubly-linked list.
type List struct {
	head *Node // sentinel head  (not accessible via cursors)
	tail *Node // sentinel tail  (not accessible via cursors)
	dum  *Info // dummy Info object with status=aborted, used as initial info
}

// NewList creates an empty list containing only the EOL marker.
func NewList() *List {
	// dummy Info object (its status is aborted so it can never "flag" a node)
	dum := &Info{}
	dum.storeStatus(aborted)

	// sentinel nodes
	head := newNode(nil, nil, nil, dum, ordinary)
	tail := newNode(nil, nil, nil, dum, ordinary)
	eol := newNode(EOL, tail, head, dum, ordinary)

	atomic.StorePointer(&head.nxt, unsafe.Pointer(eol))
	atomic.StorePointer(&tail.prv, unsafe.Pointer(eol))

	return &List{head: head, tail: tail, dum: dum}
}

// -----------------------------------------------------------------------
// Public cursor operations (Fig. 4, lines 62-73)
// -----------------------------------------------------------------------

// InitCursor initialises c to point at the first item in the list (§4).
// The caller must hold exclusive ownership of c.
func (l *List) InitCursor(c *Cursor) {
	c.node = l.head.loadNxt() // line 63
}

// DestroyCursor removes c from use.  After this call c must not be used.
func (l *List) DestroyCursor(c *Cursor) {
	c.node = nil // line 65-66 (no-op in paper; we nil for safety)
}

// ResetCursor moves c back to the first item in the list (§4).
func (l *List) ResetCursor(c *Cursor) {
	c.node = l.head.loadNxt() // line 68
}

// Get returns the value at c's current location, or InvalidCursor if c
// has been invalidated by a concurrent update.
func (l *List) Get(c *Cursor) (interface{}, OpResult) {
	y, _, _, _, invDel, _ := l.updateCursor(c) // line 71
	if invDel {
		return nil, InvalidCursor
	}
	return y.val, OK // line 73
}

// -----------------------------------------------------------------------
// MoveRight / MoveLeft (Fig. 4, lines 43-61)
// -----------------------------------------------------------------------

// MoveRight advances c one position to the right.
//
//	Returns (OK, true) on success.
//	Returns (ReturnFalse, false) if already at EOL.
//	Returns (InvalidCursor, false) if c was invalidated.
func (l *List) MoveRight(c *Cursor) (OpResult, bool) {
	y, _, z, _, invDel, _ := l.updateCursor(c) // line 57
	if invDel {
		return InvalidCursor, false
	}
	if y.val == EOL {
		return ReturnFalse, false // line 59
	}
	c.node = z  // line 60
	return OK, true
}

// MoveLeft moves c one position to the left.
//
//	Returns (OK, true) on success.
//	Returns (ReturnFalse, false) if already at the first item.
//	Returns (InvalidCursor, false) if c was invalidated.
func (l *List) MoveLeft(c *Cursor) (OpResult, bool) {
	y, _, _, x, invDel, _ := l.updateCursor(c) // line 44
	if invDel {
		return InvalidCursor, false
	}
	if x == l.head {
		return ReturnFalse, false // line 46
	}
	// line 47: test whether x is still in the list
	if x.loadPrv().loadNxt() != x && x.loadNxt() == y {
		// x is no longer reachable
		if x.loadState() == copied { // line 48: replaced by insertion
			c.node = x.loadCopy() // line 49
		} else { // line 50: deleted
			w := x.loadPrv() // line 51
			if w == l.head {
				return ReturnFalse, false // line 52
			}
			c.node = w // line 53
		}
	} else {
		c.node = x // line 54
	}
	return OK, true
}

// -----------------------------------------------------------------------
// InsertBefore (Fig. 4, lines 17-30)
// -----------------------------------------------------------------------

// InsertBefore inserts an item with value v immediately before c's location.
//
//	Returns OK on success.
//	Returns InvalidCursor if c was invalidated.
func (l *List) InsertBefore(c *Cursor, v interface{}) OpResult {
	for {
		y, yInfo, z, x, invDel, invIns := l.updateCursor(c) // line 19
		if invDel || invIns {
			return InvalidCursor // line 20
		}
		nodes := [3]*Node{x, y, z}
		oldI := [3]*Info{x.loadInfo(), yInfo, z.loadInfo()}
		if l.checkInfo(nodes, oldI) { // line 23
			newNode_ := newNode(v, nil, x, l.dum, ordinary)       // line 24
			yCopy := newNode(y.val, z, newNode_, l.dum, ordinary)  // line 25
			atomic.StorePointer(&newNode_.nxt, unsafe.Pointer(yCopy)) // line 26
			I := &Info{
				nodes:   nodes,
				oldInfo: oldI,
				newNxt:  newNode_,
				newPrv:  yCopy,
				rmv:     false,
				status:  inProgress,
			}
			if l.help(I) { // line 28
				c.node = yCopy // line 29
				return OK
			}
		}
	}
}

// -----------------------------------------------------------------------
// Delete (Fig. 4, lines 31-42)
// -----------------------------------------------------------------------

// Delete removes the item at c's current location and advances c to the
// next item.
//
//	Returns OK on success.
//	Returns ReturnFalse if c is at EOL (nothing to delete).
//	Returns InvalidCursor if c was invalidated.
func (l *List) Delete(c *Cursor) OpResult {
	for {
		y, yInfo, z, x, invDel, _ := l.updateCursor(c) // line 33
		if invDel {
			return InvalidCursor // line 34
		}
		nodes := [3]*Node{x, y, z}
		oldI := [3]*Info{x.loadInfo(), yInfo, z.loadInfo()}
		if l.checkInfo(nodes, oldI) { // line 37
			if y.val == EOL {
				return ReturnFalse // line 38
			}
			I := &Info{
				nodes:   nodes,
				oldInfo: oldI,
				newNxt:  z,
				newPrv:  x,
				rmv:     true,
				status:  inProgress,
			}
			if l.help(I) { // line 40
				c.node = z // line 41
				return OK
			}
		}
	}
}

// -----------------------------------------------------------------------
// updateCursor – internal helper (Fig. 4, lines 74-85)
// -----------------------------------------------------------------------

// updateCursor brings c.node up to date by following copy/nxt pointers
// past any replaced or deleted nodes.  It returns:
//
//	y      – the current (valid) node for c
//	yInfo  – snapshot of y.info read before y's pointer fields
//	z      – y.nxt
//	x      – y.prv
//	invDel – true if c traversed a deleted (marked) node
//	invIns – true if c traversed a replaced (copied) node
func (l *List) updateCursor(c *Cursor) (y *Node, yInfo *Info, z *Node, x *Node, invDel, invIns bool) {
	invDel = false  // line 75
	invIns = false  // line 76

	for c.node.loadPrv().loadNxt() != c.node { // line 77: c.node not in list
		st := c.node.loadState()
		if st == copied { // line 78
			invIns = true           // line 79
			c.node = c.node.loadCopy() // line 80
		} else if st == marked { // line 81
			invDel = true           // line 82
			c.node = c.node.loadNxt() // line 83
		}
		// If neither copied nor marked, the node may be in the middle of
		// being flagged; loop again to re-check.
	}

	// Read info before nxt/prv so we have a consistent snapshot (line 84).
	yInfo = c.node.loadInfo()
	y = c.node
	z = y.loadNxt() // line 85
	x = y.loadPrv()
	return
}

// -----------------------------------------------------------------------
// checkInfo – detect interference (Fig. 4, lines 86-95)
// -----------------------------------------------------------------------

// checkInfo returns true iff it detects no interference on nodes.
// If another update is in progress on any of the nodes, it helps that
// update and returns false (causing the caller to retry).
func (l *List) checkInfo(nodes [3]*Node, oldInfo [3]*Info) bool {
	// Check for in-progress updates (lines 87-90)
	for i := 0; i < 3; i++ {
		if oldInfo[i].loadStatus() == inProgress {
			l.help(oldInfo[i]) // line 89: help the other update
			return false        // line 90
		}
	}
	// Check for removed nodes (lines 91-92)
	for i := 0; i < 3; i++ {
		if nodes[i].loadState() != ordinary {
			return false
		}
	}
	// Check if info of 2nd or 3rd node has changed (lines 93-94)
	for i := 1; i < 3; i++ {
		if nodes[i].loadInfo() != oldInfo[i] {
			return false
		}
	}
	return true // line 95
}

// -----------------------------------------------------------------------
// help – perform the real work of an update (Fig. 4, lines 96-111)
// -----------------------------------------------------------------------

// help attempts to complete the update described by I.
// Returns true iff I.status ends up committed.
func (l *List) help(I *Info) bool {
	doPtrCAS := true // line 97
	i := 0

	// Flag CAS steps (lines 98-101)
	for i < 3 && doPtrCAS {
		I.nodes[i].casInfo(I.oldInfo[i], I) // line 99 – flag CAS
		doPtrCAS = (I.nodes[i].loadInfo() == I)
		i++
	}

	if doPtrCAS { // line 102: all three flag CASes succeeded
		if I.rmv { // line 103: deletion
			I.nodes[1].storeState(marked)
		} else { // line 104-106: insertion
			I.nodes[1].storeCopy(I.newPrv)  // line 105: set copy pointer
			I.nodes[1].storeState(copied)   // line 106
		}
		// Forward CAS: change x.nxt from y to newNxt (line 107)
		I.nodes[0].casNxt(I.nodes[1], I.newNxt)
		// Backward CAS: change z.prv from y to newPrv (line 108)
		I.nodes[2].casPrv(I.nodes[1], I.newPrv)
		I.storeStatus(committed) // line 109: unflag by committing
	} else if I.loadStatus() == inProgress {
		I.storeStatus(aborted) // line 110: unflag by aborting
	}

	return I.loadStatus() == committed // line 111
}

// -----------------------------------------------------------------------
// Convenience / debugging helpers (not part of the paper's interface)
// -----------------------------------------------------------------------

// Len counts the number of non-EOL items currently in the list.
// This is a non-atomic snapshot walk and is intended for testing only.
func (l *List) Len() int {
	n := 0
	cur := l.head.loadNxt()
	for cur != l.tail {
		if cur.val != EOL {
			n++
		}
		cur = cur.loadNxt()
	}
	return n
}

// Snapshot returns a slice of all current values (excluding EOL) in
// left-to-right order.  Like Len, this is for testing / debugging only.
func (l *List) Snapshot() []interface{} {
	var out []interface{}
	cur := l.head.loadNxt()
	for cur != l.tail {
		if cur.val != EOL {
			out = append(out, cur.val)
		}
		cur = cur.loadNxt()
	}
	return out
}

// String returns a simple string representation of the list.
func (l *List) String() string {
	return fmt.Sprintf("List%v", l.Snapshot())
}
